# Generated by Django 5.2.15 on 2026-06-07 14:31

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dcim", "0084_add_module_type_image_support"),
        ("extras", "0142_remove_scheduledjob_approval_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("carrier_name", models.CharField(db_index=True, max_length=255)),
                ("apn", models.CharField(max_length=255)),
                ("authentication_type", models.CharField(default="none", max_length=32)),
                ("roaming_allowed", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Carrier Profile",
                "verbose_name_plural": "Carrier Profiles",
                "ordering": ["carrier_name", "name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CellularRouter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("imei", models.CharField(db_index=True, max_length=15, unique=True)),
                ("provisioning_state", models.CharField(db_index=True, default="planned", max_length=32)),
                ("vendor_platform", models.CharField(blank=True, max_length=64)),
                ("external_system_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cellular_router", to="dcim.device"
                    ),
                ),
                (
                    "modem_interface",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cellular_router", to="dcim.interface"
                    ),
                ),
                (
                    "modem_inventory_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cellular_router",
                        to="dcim.inventoryitem",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Cellular Router",
                "verbose_name_plural": "Cellular Routers",
                "ordering": ["device__name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CellularOperationalSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("collector", models.CharField(max_length=128)),
                ("registration_state", models.CharField(db_index=True, default="unknown", max_length=32)),
                ("rssi_dbm", models.SmallIntegerField(blank=True, null=True)),
                ("rsrp_dbm", models.SmallIntegerField(blank=True, null=True)),
                ("rsrq_db", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("sinr_db", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("observed_iccid", models.CharField(blank=True, db_index=True, max_length=22)),
                ("payload_hash", models.CharField(max_length=64)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "router",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_snapshot",
                        to="nautobot_cellular_sot.cellularrouter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cellular Operational Snapshot",
                "verbose_name_plural": "Cellular Operational Snapshots",
                "ordering": ["-observed_at"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SIMCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("iccid", models.CharField(db_index=True, max_length=22, unique=True)),
                ("imsi", models.CharField(blank=True, db_index=True, max_length=15)),
                ("msisdn", models.CharField(blank=True, db_index=True, max_length=32)),
                ("slot", models.CharField(blank=True, max_length=16)),
                ("provisioning_state", models.CharField(db_index=True, default="planned", max_length=32)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "carrier_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sim_cards",
                        to="nautobot_cellular_sot.carrierprofile",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sim_cards",
                        to="nautobot_cellular_sot.cellularrouter",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "SIM Card",
                "verbose_name_plural": "SIM Cards",
                "ordering": ["iccid"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="cellularrouter",
            constraint=models.UniqueConstraint(
                fields=("device", "modem_interface"), name="cellular_sot_unique_device_interface"
            ),
        ),
        migrations.AddConstraint(
            model_name="simcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("router__isnull", False), models.Q(("slot", ""), _negated=True)),
                fields=("router", "slot"),
                name="cellular_sot_unique_router_slot",
            ),
        ),
    ]
