---
name: "Dependency Review"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  dependency-review:
    name: "Dependency Review"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Review dependency changes"
        uses: "actions/dependency-review-action@v4"
        with:
          fail-on-severity: "high"
          comment-summary-in-pr: "on-failure"
          vulnerability-check: true
          license-check: true
